apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cRYP70n-13/nginx-gitops.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc
