apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: foo
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image: otmaneki/nginx:v0.1.0
